### ISSUE TITLE
[NTK] Next routing don't loads new page

### ISSUE THREAD

**Issue by kaluabentes** [CheesecakeLabs/react-next-boilerplate#6]
For any reason the Next router don't loads a page when its first requested, this happens both for `<Link>` transitions and imperative `Router.push()` calls.

**Comment by dleitee** [comment]
Hey @kaluabentes 

Can you give me the `project name` and the `branch` are you working?

**Comment by dleitee** [comment]
I'm running the branch `dev` on `ntk` project and got an error related to routes.

When I click to go to another route, the Webapp go to the new route and then returns to the old route instantly.

That is it that was occurring on your end, right?

And this event only occurs with a route that you have never opened, right?

**Comment by dleitee** [comment]
I've opened a PR into `ntk` project about this issue.

So, I just put a new option into `next.config.js`:
```es6
{ 
   distDir: '../dist',
}
```

**TODO:**
- [x] Add distDir as a option into `next.config.js` at boilerplate.

**Comment by dleitee** [comment]
Already fixed.
