### ISSUE TITLE
[Components] Leaflet support server-side rendering

### ISSUE THREAD

**Issue by beatriz1304** [CheesecakeLabs/react-next-boilerplate#7]
> Leaflet makes direct calls to the DOM when it is loaded, therefore this library is not compatible with server-side rendering.

My solution was set the variables on componentDidMount but I think it's not the best practice and I wanna know your opinion for a better and cleaner code

```
componentDidMount() {
    let RL = require('react-leaflet')
    Map = RL.Map
    TileLayer = RL.TileLayer
    Marker = RL.Marker
    Popup = RL.Popup

    this.setState({ showMap: true })
  }
```
I found this lib (https://github.com/masotime/react-leaflet-universal) but with this I can not use the component directly

**Comment by dleitee** [comment]
I don't think you need a server-side rendering for the map, so you can verify if there is a `window` object then if it exists, render the `leaflet` map.

```jsx
renderMap = () => {
  if (window) {
    return (<Map />)
  }
  return null
}

render ( ) {
   return (
      <div>{renderMap()}</div>
   )
}
```
